import { Router } from "express";
import createPurchase from "../controllers/transaction/create-purchase";
import updatePurchase from "../controllers/transaction/update-purchase";
import createSettleUp from "../controllers/transaction/create-settleup";
import updateSettleUp from "../controllers/transaction/update-settleup";
import createBill from "../controllers/transaction/create-bill";
import updateBill from "../controllers/transaction/update-bill";
import getBalances from "../controllers/transaction/get-balance";
import getUserTransactions from "../controllers/transaction/get-transactions-for-user";
import getTransactionsBetweenUsers from "../controllers/transaction/get-transactions-for-userpair";
import deleteTransaction from "../controllers/transaction/delete-transaction";
import createRecurringTemplate from "../controllers/transaction/create-recurring-template";
import getUserRecurringTemplates from "../controllers/transaction/get-recurring-templates-for-user";
import deleteTemplate from "../controllers/transaction/delete-recurring-template";
import updateRecurringTemplate from "../controllers/transaction/update-recurring-template";
import getUserSpending from "../controllers/transaction/get-user-spending";
import scanReceipt from "../controllers/transaction/scan";
import getSmartSettle from "../controllers/transaction/get-smart-settle";
import createSmartSettle from "../controllers/transaction/create-smart-settle";
import recalculateBalances from "../controllers/transaction/recalculate-balances";
import getBalancesLegacy from "../controllers/transaction/get-balance-legacy";
import verifyBalance from "../controllers/transaction/verify-balance";
import verifyAllBalances from "../controllers/transaction/verify-all-balances";

const router = Router();

router.post("/purchase/create", createPurchase);
router.put("/purchase/update/:transactionId", updatePurchase);
router.post("/settleup/create", createSettleUp);
router.put("/settleup/update/:transactionId", updateSettleUp);
router.post("/bill/create", createBill);
router.put("/bill/update/:transactionId", updateBill);
router.post("/recurring/create", createRecurringTemplate);
router.get("/balances/:userId", getBalances);
router.get("/balances/legacy/:userId", getBalancesLegacy);
router.get("/verify-all", verifyAllBalances);
router.get("/verify/:userId", verifyBalance);
router.get("/all/:userId", getUserTransactions);
router.get("/recurring/:userId", getUserRecurringTemplates);
router.get("/all/:userId1/:userId2", getTransactionsBetweenUsers);
router.delete("/:transactionId", deleteTransaction);
router.delete("/recurring/:templateId", deleteTemplate);
router.put("/recurring/update/:templateId", updateRecurringTemplate);
router.get("/spending/:userId", getUserSpending);
router.post("/smart-settle", getSmartSettle);
router.post("/smart-settle/create", createSmartSettle);

router.post("/scan", scanReceipt);
router.post("/recalculate", recalculateBalances);

export default router;
